### ISSUE TITLE
HDR Steamdeck question

### ISSUE THREAD

**Issue by WybeBosch** [ILOVEPIE/HDRDeck#4]
This is deff not the right place to ask this, but since you seem to be in the know about the Steamdeck HDR support. 

- I read that HDR doesnt work in desktop mode, only in gaming mode. 
- Would it be possible to play 4k HDR movie while in gaming mode by adding the video player to steam as a nonsteam game?

Or does linux simply not support playing HDR content other than video games?

**Comment by ILOVEPIE** [comment]
HDR support is not available in desktop mode yet because there's a lot of work that needs to be done for both the desktop and other components of Linux. Also worth mentioning is the fact that HDR support currently requires use of either Vulkan or DirectX 12 in order to work and the video players that you would use for playing 4K videos in HDR are going to need to use one of those two APIs in order to display in HDR. Linux video players as a general rule of thumb don't support HDR yet however you might be able to get a Windows player working in HDR via Proton.

**Comment by WybeBosch** [comment]
Thanks for your response! Its been quite a journey figuring out the ins and outs of my Steamdeck. 
Il give your emulation proton suggestions a try, been having blast so far watching Media on the steamdeck as compared to my Phone since the screen is so good!

Again, thanks for the response and have a good day!
